factory: form
name: ugm_general
props:
    action: context.form_action
    class: ajax
widgets:
- default_membership_assignment_widget:
    factory: field:label:select
    value: expr:context.model.attrs.default_membership_assignment_widget
    props:
        label: Default membership assignment widget
        vocabulary: expr:[('listing', 'Listing'), ('inout', 'In-Out')]
- user_display_name_attr:
    factory: field:label:text
    value: expr:context.model.attrs.user_display_name_attr
    props:
        label: User display name attribute
- group_display_name_attr:
    factory: field:label:text
    value: expr:context.model.attrs.group_display_name_attr
    props:
        label: Group display name attribute
- users_account_expiration:
    factory: field:label:checkbox
    value: expr:context.model.attrs.users_account_expiration == 'True'
    props:
        label: User Accounts expires?
        help: Flag whether to consider user expiration
- users_expires_attr:
    factory: field:label:text
    value: expr:context.model.attrs.users_expires_attr
    props:
        label: Attribute containing expiration Time
        help: LDAP attribute name containing expires information
- users_expires_unit:
    factory: field:label:select
    value: expr:int(context.model.attrs.users_expires_unit)
    props:
        label: Account expiration unit
        help: Unit of expiration value
        vocabulary: expr:((0, 'Days since Epoch'), (1, 'Seconds since epoch'))
- user_id_autoincrement:
    factory: field:label:checkbox
    value: expr:context.model.attrs.user_id_autoincrement == 'True'
    props:
        label: Autoincrement user id
        help: "Flag whether to autoincrement user ids at user creation time. 
               This feature only works for systems using numeric user ID's"
- user_id_autoincrement_prefix:
    factory: field:label:text
    value: expr:context.model.attrs.user_id_autoincrement_prefix
    props:
        label: Autoincrement user id prefix
        help: Prefix for autogenerated user ID's
- user_id_autoincrement_start:
    factory: field:label:error:number
    value: expr:int(context.model.attrs.user_id_autoincrement_start)
    props:
        label: Autoincrement initial user number
        help: User number to start from
        datatype: integer
- users_portrait:
    factory: field:label:checkbox
    value: expr:context.model.attrs.users_portrait == 'True'
    props:
        label: Portrait Support
        help: Flag whether users can have a portrait
- users_portrait_attr:
    factory: field:label:text
    value: expr:context.model.attrs.users_portrait_attr
    props:
        label: Attribute containing portrait image
        help: LDAP attribute name containing portrait image
- users_portrait_accept:
    factory: field:label:text
    value: expr:context.model.attrs.users_portrait_accept
    props:
        label: Portrait mimetype
        help: Accepted Image mimetype for portrait property
- users_portrait_width:
    factory: field:label:error:number
    value: expr:int(context.model.attrs.users_portrait_width)
    props:
        label: Portrait width
        help: Width in pixel portrait gets scaled to
        datatype: integer
- users_portrait_height:
    factory: field:label:error:number
    value: expr:int(context.model.attrs.users_portrait_height)
    props:
        label: Portrait height
        help: Height in pixel portrait gets scaled to
        datatype: integer
- save:
    factory: submit
    props:
        action: save
        expression: True
        handler: context.save
        next: context.next
        label: Save