factory: form
name: localmanager_settings
props:
    action: context.form_action
    class: ajax
widgets:
- rules:
    factory: field:array
    value: expr:context.rules_value
    props:
        label: i18n:localmanager_rules
        sort: False
        table_class: rules_array
    widgets:
    - rule:
            factory: compound
            widgets:
            - source:
                factory: field:label:error:autocomplete
                props:
                    label: i18n:localmanager_rule_source
                    required: i18n:localmanager_source_empty
                    source: javascript:ugm.localmanager.autocomplete_gid
                    minLength: 1
                    delay: 300
                    class: source_field
            - targets:
                factory: error:array
                props:
                    label: i18n:localmanager_rule_target
                    required: i18n:localmanager_no_targets_for_source
                    sort: False
                    class: array targets_field
                    table_class: targets_array
                widgets:
                - target:
                    factory: compound
                    widgets:
                    - gid:
                        factory: error:*notsource:autocomplete
                        props:
                            required: i18n:localmanager_target_empty
                            source: javascript:ugm.localmanager.autocomplete_gid
                            minLength: 1
                            delay: 300
                        custom:
                            notsource:
                                extractors:
                                    - context.target_not_source
                    - default:
                        factory: checkbox
                        props:
                            class: target_default
- save:
    factory: submit
    props:
        action: save
        expression: True
        handler: context.save
        next: context.next
        label: i18n:save